name: Deploy Website to Hostinger

on:
 push:
   branches:
     - main  # Triggers the action when you push to the main branch

jobs:
 web-deploy:
   name: Deploy
   runs-on: ubuntu-latest
   steps:
   - name: 🚚 Get latest code
     uses: actions/checkout@v4

   - name: 📂 Sync files to Hostinger
     uses: SamKirkland/FTP-Deploy-Action@v4.3.5
     with:
       server: ${{ secrets.FTP_SERVER }}
       username: ${{ secrets.FTP_USERNAME }}
       password: ${{ secrets.FTP_PASSWORD }}
       server-dir: /public_html/  # Adjust if your files go to a specific subfolder
